lab4 attempt1
ned8800/IU5-Frontend-2022 pull request #4
Opened 2022-03-20 19:19 UTC by ned8800

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Убедись, что поднялся vercel с твоей работой и бот написал тебе коментарий в пре со ссылкой.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ master
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, мы поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь зеленую галочку от нас на пре, можешь смержить PR.

- [ ] Ты увидел зеленую галочку от нас на пре?

2022-03-21 16:56 UTC, antoffee requested changes

2022-03-21 16:56 UTC, antoffee commented on lab3/1.js
> +    let i = 0;
Почему тут третья лаба? Сделай так, чтобы в ПРе была только 4

2022-03-21 19:04 UTC, ned8800 commented on lab3/1.js
> +    let i = 0;
Готово

2022-03-23 09:34 UTC, antoffee requested changes
Я на лекции говорила, что надо не удалять файлы - ты так лабу потеряешь, а разобраться с тем, где что криво смержилось и поправить. Ну и третья лаба до сих пор здесь. Поправь, пожалуйста
<img width="474" alt="image" src="https://user-images.githubusercontent.com/70894124/159668151-4a1bf490-b80f-4e09-a032-36c64369c063.png">

2022-03-27 22:32 UTC, merged